# Generated by Django 4.0.5 on 2022-07-01 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('Id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200, unique=True)),
                ('Forewords', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('Id', models.BigIntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=1000)),
                ('isbn', models.BigIntegerField()),
                ('price', models.FloatField()),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.author')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
