# Generated by Django 4.0.5 on 2022-07-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Description',
            field=models.TextField(max_length=1000),
        ),
    ]
