# Generated by Django 4.0.5 on 2022-07-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isbn',
            new_name='ISBN',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='price',
            new_name='Price',
        ),
        migrations.AlterField(
            model_name='book',
            name='Id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
