# Generated by Django 4.0.5 on 2022-07-01 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_rename_isbn_book_isbn_rename_price_book_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='ISBN',
            new_name='isbn',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Title',
            new_name='title',
        ),
    ]
