# Generated by Django 4.0.5 on 2022-07-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_rename_author_book_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13),
        ),
    ]
