# The compose file produced 28.06.22

version: "3.7"

networks:
  core:

services:

  # postgres database
  postgres:
    container_name: "postgres"
    image: "postgres:13"
    hostname: "postgres-localhost"
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      - POSTGRES_DB=bbmlogistica
      - POSTGRES_USER=dialogo
      - POSTGRES_PASSWORD=myDybBuniouzADDwFhQaj271
    volumes:
      - /tmp/volumes/bbmlogistica/data:/var/lib/postgresql/data
    networks:
      - core

  # redis data cache or reduce data latency
  redis:
    container_name: "redis"
    image: "redis:7.0.2"
    hostname: "redis-localhost"
    ports:
      - "0.0.0.0:6379:6379"
    environment:
      - REDIS_PASSWORD=gzeNhBmy5TdEepdWkAH4Dj2y
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    networks:
      - core

  # django application definitions
  app:
    container_name: "app"
    build:
      context: .
      dockerfile: "Dockerfile"
      args:
        - ENVIRONMENT=develop
    hostname: "application-localhost"
    ports:
      - "0.0.0.0:8080:8080"
    command: "gunicorn djangoProject.asgi:application -b :8080 -w 2 -k uvicorn.workers.UvicornWorker"
    depends_on:
      - postgres
      - redis
    networks:
      - core
