# Generated by Django 4.0.5 on 2022-07-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_alter_author_forewords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='Id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
