# Generated by Django 4.0.5 on 2022-07-01 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_alter_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Forewords',
            new_name='forewords',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='Id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='Name',
            new_name='name',
        ),
    ]
